# -*- coding: utf-8 -*-
"""firstassignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3ssz1gnqkMz_0j_1MzjFeqqS5-QUdeS
"""

# ==========================================
# PART 1: Data Structures, Loops & Cleaning
# ==========================================
climate_data = [
    {"station": "Damascus", "temperature": 38.5, "rainfall": 10.0, "humidity": 20},
    {"station": "Aleppo", "temperature": 40.2, "rainfall": 8.5, "humidity": 15},
    {"station": "Latakia", "temperature": 31.0, "rainfall": 12.5, "humidity": 75},
    {"station": "Homs", "temperature": 36.0, "rainfall": 2.0, "humidity": 35},
    {"station": "Deir ez-Zor", "temperature": None, "rainfall": 0.0, "humidity": 10}
]

print("=== PART 1: Climate Data Summary ===")
total_temp = 0
valid = 0
high = float('-inf')
low = float('inf')
high_temp_station = ""
low_temp_station = ""
classifications = {}

for record in climate_data:
    station = record["station"]
    temp = record["temperature"]

    if temp is None:
        print(f"Skipping station {station} due to missing temperature data.")
        continue

    valid += 1
    total_temp += temp

    if temp > high:
        high = temp
        high_temp_station = station

    if temp < low:
        low = temp
        low_temp_station = station

    print(f"Station: {station} | Temp: {temp}°C | Rainfall: {record['rainfall']}mm | Humidity: {record['humidity']}%")

    if temp >= 40.0:
        category = "Extreme Heat"
    elif temp >= 35.0:
        category = "High Heat"
    elif temp >= 30.0:
        category = "Moderate Heat"
    else:
        category = "Normal"

    print(f"The temperature in {station} is {category}.")
    classifications[station] = category

avg_temp = total_temp / valid
print(f"\nValid observations: {valid}")
print(f"Average Temperature across all stations: {avg_temp:.2f}°C")
print(f"Highest Temperature: {high}°C in {high_temp_station}")
print(f"Lowest Temperature: {low}°C in {low_temp_station}")
print("Final Classifications Dictionary:")
print(classifications)


# ==========================================
# PART 2: Functions & Climate Risk Assessment
# ==========================================
def calculate_risk(temperature, rainfall):
    if temperature >= 40:
        return "EXTREME"
    elif temperature >= 35 or rainfall < 5:
        return "HIGH"
    elif temperature >= 30 or rainfall < 15:
        return "MODERATE"
    else:
        return "LOW"

print("\n=== PART 2: Risk Observation ===")
for record in climate_data:
    station = record["station"]
    temp = record["temperature"]
    rainfall = record["rainfall"]
    if temp is None:
        continue
    risk = calculate_risk(temp, rainfall)
    print(f"Station {station} | Temp: {temp}°C | Risk: {risk}")

def get_stats(temp_list):
    avg = sum(temp_list) / len(temp_list)
    max_val = max(temp_list)
    min_val = min(temp_list)
    return (avg, min_val, max_val)

valid_temps = []
valid_cities = []

for record in climate_data:
    temp = record["temperature"]
    if temp is None:
        continue
    valid_temps.append(temp)
    valid_cities.append(record)

stats = get_stats(valid_temps)

print("\n=== Stats Summary (Tuple) ===")
print(f"Average temperature is: {stats[0]:.2f}°C")
print(f"Lowest temperature is: {stats[1]}°C")
print(f"Highest temperature is: {stats[2]}°C")

print("\n=== High Risk Alert ===")
for city in valid_cities:
    risk = calculate_risk(city["temperature"], city["rainfall"])
    city["risk"] = risk
    if risk in ["HIGH", "EXTREME"]:
        print(f"ALERT: The {city['station']} temp is {city['temperature']}°C | Risk: {city['risk']}")

sorted_cities = sorted(valid_cities, key=lambda x: x["temperature"], reverse=True)
print("\n=== Cities Sorted by Temperature (Descending) ===")
for city in sorted_cities:
    print(f"City: {city['station']} | Temperature: {city['temperature']}°C")


# ==========================================
# PART 3: Object-Oriented Programming (OOP)
# ==========================================
class ClimateStation:
    def __init__(self, city, temperature, humidity, rainfall):
        self.city = city
        self.temperature = temperature
        self.humidity = humidity
        self.rainfall = rainfall

    def display_summary(self):
        print(f"Station: {self.city} | Temp: {self.temperature}°C | Humidity: {self.humidity}% | Rainfall: {self.rainfall}mm")

    def calculate_risk(self):
        if self.temperature >= 40:
            return "EXTREME"
        elif self.temperature >= 35 or self.rainfall < 5:
            return "HIGH"
        elif self.temperature >= 30 or self.rainfall < 15:
            return "MODERATE"
        else:
            return "LOW"

    def update_temperature(self, new_temperature):
        self.temperature = new_temperature
        print(f"Updated temperature for {self.city} to {self.temperature}°C")

    def recommendation(self):
        risk = self.calculate_risk()
        if risk == "LOW":
            return "Normal monitoring"
        elif risk == "MODERATE":
            return "Continue monitoring"
        elif risk == "HIGH":
            return "Increased monitoring recommended"
        elif risk == "EXTREME":
            return "Immediate attention required"

print("\n=== PART 3: OOP Stations Implementation ===")
s1 = ClimateStation("Damascus", 38.5, 20, 10.0)
s2 = ClimateStation("Aleppo", 40.2, 15, 8.5)
s3 = ClimateStation("Latakia", 31.0, 75, 12.5)
s4 = ClimateStation("Homs", 36.0, 35, 2.0)
s5 = ClimateStation("Daraa", 29.0, 40, 10.0)

stations_list = [s1, s2, s3, s4, s5]

for station in stations_list:
    station.display_summary()
    risk = station.calculate_risk()
    rec = station.recommendation()
    print(f"  -> Risk Level: {risk} | Action: {rec}\n")

print("=== Updating Temperature Example ===")
s5.update_temperature(33.5)
s5.display_summary()

class SmartClimateStation(ClimateStation):
    def __init__(self, city, temperature, humidity, rainfall, sensor_status="Active"):
        super().__init__(city, temperature, humidity, rainfall)
        self.sensor_status = sensor_status

    def check_sensor(self):
        print(f"Smart Station {self.city} | Sensor Status: {self.sensor_status}")

print("\n=== SmartClimateStation Class Demo ===")
smart_s = SmartClimateStation("Deir ez-Zor", 42.0, 10, 0.0, sensor_status="Active")
smart_s.display_summary()
smart_s.check_sensor()
print(f"Risk: {smart_s.calculate_risk()} | Action: {smart_s.recommendation()}")